[package]
name = "brt"
version = "0.1.3"
authors = ["Jan Willems <jw@elevenbits.com>"]
keywords = ["terminal", "btop"]
repository = "https://github.com/jw/brt"
readme = "README.md"
edition = "2021"
description = "btop in rust"
license = "EUPL-1.2"
rust-version = "1.74.1"

[[bin]]
name = "brt"


[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.1"
anyhow = "1.0.79"
itertools = "0.12.1"
log = "0.4.20"
dirs = "5.0.1"
log4rs = "1.3.0"
chrono = "0.4.34"
battery = "0.7.8"
clap = { version = "4.5.1", features = ["derive"] }
procfs = "0.16.0"
uzers = "0.11.3"
