[package]
name = "brt"
version = "0.1.8"
authors = ["Jan Willems <jw@elevenbits.com>"]
keywords = ["terminal", "btop"]
repository = "https://github.com/jw/brt"
readme = "README.md"
edition = "2021"
description = "btop in rust"
license = "EUPL-1.2"
rust-version = "1.74.1"

[[bin]]
name = "brt"

[dependencies]
battery = "0.7.8"
chrono = "0.4.40"
color-eyre = "0.6.3"
crossterm = { version = "0.29.0", features = ["serde", "event-stream"] }
ratatui = { version = "0.30.0-alpha.2", features = ["default", "unstable-widget-ref"] }
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.17"


[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
