[package]
name = "brt"
version = "0.1.4"
authors = ["Jan Willems <jw@elevenbits.com>"]
keywords = ["terminal", "btop"]
repository = "https://github.com/jw/brt"
readme = "README.md"
edition = "2021"
description = "btop in rust"
license = "EUPL-1.2"
rust-version = "1.74.1"

[[bin]]
name = "brt"

[[bin]]
name = "processbar"
path = "src/processbar.rs"

[dependencies]
anyhow = "1.0.81"
battery = "0.7.8"
better-panic = "0.3.0"
chrono = "0.4.35"
clap = { version = "4.5.2", features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "cargo", "wrap_help", "unicode", "string", "unstable-styles"] }
color-eyre = "0.6.2"
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
directories = "5.0.1"
dirs = "5.0.1"
futures = "0.3.30"
humansize = "2.1.3"
itertools = "0.12.1"
lazy_static = "1.4.0"
libc = "0.2.153"
log = "0.4.21"
log4rs = "1.3.0"
nix = "0.28.0"
owo-colors = "4.0.0"
procfs = "0.16.0"
json5 = "0.4.1"
ratatui = "0.26.1"
serde = { version = "1.0.196", features = ["derive"] }
signal-hook = "0.3.17"
strip-ansi-escapes = "0.2.0"
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.10"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "serde"] }
uzers = "0.11.3"
config = "0.14.0"
serde_json = "1.0.113"
pretty_assertions = "1.4.0"
derive_deref = "1.1.1"
tui-input = { version = "0.8.0", features = ["serde"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
